apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-api-deploy
  namespace: device-api-env
  labels: 
    app: device-api
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: device-api-lbl
  template: 
    metadata:
      labels:
        app: device-api-lbl
    spec:
      containers:
      - name: device-api-cntnr
        image: device-api:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: device-db-config
              key: mysql-url
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: device-db-config
              key: mysql-db-name        
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: device-db-secret
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: device-db-secret
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: device-api-ser
  namespace: device-api-env
spec:
  type: NodePort
  selector:
    app: device-api-lbl
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100