version: '3'
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=mysqlpwd
     - MYSQL_DATABASE=userapi
     - MYSQL_USER=userapi
     - MYSQL_PASSWORD=userapi
  device-api:
    image: device-api:1.0
    ports:
     - 4000:3000
    environment:
     - DB_URI=mysqldb
     - DB_NAME=userapi
     - DB_USERNAME=userapi
     - DB_PASSWORD=userapi